spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Vinod@14293
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8082
  
eureka:
  instance:
    preferIpAddress:true
    hostname:eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  eureka:
    instance:
      hostname: localhost
